services:
  dev:
    build:
      context: ${BUILD_DIR:-.}
      dockerfile: .docker/dockerfile.dev
      args: 
        - BASE_IMAGE=${BASE_IMAGE:-ros:jazzy-ros-base}
        - ROS_DISTRO=${ROS_DISTRO:-jazzy}
        - WORKSPACE=${WORKSPACE_DIR:-/workspace}
    image: byu_boat_core:${ROS_DISTRO:-jazzy}
    container_name: boat_dev
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ${WORKSPACE_SRC:-./src}:${WORKSPACE_DIR:-/workspace}/src
      - /dev:/dev
    environment:
      - ROS_DISTRO=${ROS_DISTRO:-jazzy}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-10}