ARG BASE_IMAGE=ros:jazzy-ros-base

FROM ${BASE_IMAGE}

ARG ROS_DISTRO=jazzy
ARG WORKSPACE=/workspace

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    python3-colcon-common-extensions \
    python3-pip \
    udev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR $WORKSPACE



COPY .docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]